version: '3.7'

services:

  mesi-io-frontend:
    image: mesi/web
    container_name: mesi-io-frontend

    ports:
      - 40100:80

    healthcheck:
      test: curl -f http://localhost:80 || exit 1
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 1m
